"""Initial schema setup

Revision ID: fb19adb14241
Revises: 
Create Date: 2026-08-13 09:37:43.679809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fb19adb14241'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scans_id'), table_name='scans')
    op.drop_table('scans')
    op.create_index(op.f('ix_alerts_id'), 'alerts', ['id'], unique=False)
    op.create_index(op.f('ix_detection_logs_id'), 'detection_logs', ['id'], unique=False)
    op.create_index(op.f('ix_entrance_records_id'), 'entrance_records', ['id'], unique=False)
    op.alter_column('parking_slots', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'Available'::character varying"))
    op.create_index(op.f('ix_parking_slots_id'), 'parking_slots', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_parking_slots_id'), table_name='parking_slots')
    op.alter_column('parking_slots', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'Available'::character varying"))
    op.drop_index(op.f('ix_entrance_records_id'), table_name='entrance_records')
    op.drop_index(op.f('ix_detection_logs_id'), table_name='detection_logs')
    op.drop_index(op.f('ix_alerts_id'), table_name='alerts')
    op.create_table('scans',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('plate_number', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('is_registered', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('snap_path', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('scanned_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('vehicle_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('scans_pkey'))
    )
    op.create_index(op.f('ix_scans_id'), 'scans', ['id'], unique=False)
    # ### end Alembic commands ###
