"""
=========================================================
Sri Lankan Number Plate Validator & Normalizer
=========================================================

Author : Senitha Kahatapitiya / Updated for ANPR v4

Master normalization & validation pipeline for Sri Lankan
vehicle license plates.

Supports:
1. Civilian modern plates:
   - Modern-2: 2 letters + 4 digits (e.g. CA-1234)
   - Modern-3: 3 letters + 4 digits (e.g. CDD-3435)
   - Confident civilian province prefix removal (WP, CP, SP, NP, EP, NC, NW, SG, UP)
2. Sri Series plates (ශ්රී / ශ්‍රී / SRI):
   - 1 to 3 digits + SRI marker + 1 to 4 digits -> [LEADING]-[TRAILING] (e.g. 1-1234, 15-3201, 301-5678)
3. Military vehicles:
   - Air Force: ගුවන් / AIR -> AIR-XXXX (e.g. AIR-1234)
   - Navy: නාහ / NAVY -> NAVY-XXXX (e.g. NAVY-5678)
   - Army: යුහ / ARMY -> ARMY-XXXX (e.g. ARMY-4321)
4. Special / Unknown plates:
   - Unrecognized prefixes preserved (e.g. GGCA1234 -> GGCA-1234)
"""

import re
import unicodedata
from typing import Dict, Optional, Tuple, Any

# Sri Lankan Provinces
PROVINCES = {"WP", "CP", "SP", "NP", "EP", "NC", "NW", "SG", "UP"}

# Sri Series Regex (Sinhala variations with/without ZWJ and English)
SRI_SINHALA_REGEX = re.compile(
    r"^(\d{1,3})\s*[-]?\s*(?:ශ[\u200D\s]*්[\u200D\s]*ර[\u200D\s]*[ීි]|ශ්රී|ශ්‍රී)\s*[-]?\s*(\d{1,4})$"
)
SRI_ENGLISH_REGEX = re.compile(r"^(\d{1,3})\s*[-]?\s*SRI\s*[-]?\s*(\d{1,4})$", re.IGNORECASE)

# Military Vehicle Regex (Sinhala and English identifiers)
AIR_FORCE_SINHALA = re.compile(r"^(?:ගුවන්|ග\s*ු\s*ව\s*න\s*්)\s*[-]?\s*(\d{4,5})$")
AIR_FORCE_ENGLISH = re.compile(r"^AIR\s*[-]?\s*(\d{4,5})$", re.IGNORECASE)

NAVY_SINHALA = re.compile(r"^(?:නාහ|න\s*ා\s*හ)\s*[-]?\s*(\d{4,5})$")
NAVY_ENGLISH = re.compile(r"^NAVY\s*[-]?\s*(\d{4,5})$", re.IGNORECASE)

ARMY_SINHALA = re.compile(r"^(?:යුහ|ය\s*ු\s*හ)\s*[-]?\s*(\d{4,5})$")
ARMY_ENGLISH = re.compile(r"^ARMY\s*[-]?\s*(\d{4,5})$", re.IGNORECASE)


def normalize_sri_series(text: str) -> Optional[Tuple[str, str]]:
    """
    Dedicated Sri-Marker normalization stage.
    Parses Sri-Series plates with Sinhala/English Sri markers into canonical [leading]-[trailing] format.
    
    Processing Architecture:
    RAW OCR -> Unicode normalization -> Detect Sri cluster -> Extract digits -> Validate structure -> Canonical result
    """
    if not text:
        return None

    # 1. Unicode NFC normalization
    norm_text = unicodedata.normalize("NFC", str(text).strip())

    # 2. English SRI marker check: e.g. "13 SRI 3436", "13-SRI-3436", "13 SRI 3 436"
    m_eng = re.match(r"^(\d{1,3})[\s\-_|·•~]*SRI[\s\-_|·•~]*(.*)$", norm_text, re.IGNORECASE)
    if m_eng:
        leading = m_eng.group(1)
        trailing_digits = re.sub(r"\D", "", m_eng.group(2))
        if 1 <= len(trailing_digits) <= 4:
            return f"{leading}-{trailing_digits}", "Sri-Series"

    # 3. Sinhala Sri marker cluster detection:
    # Matches: "13 ශ්‍රී 3436", "13 ශ්රී 3436", "13 ශ්ර 3436", "13 ශර ශ්ර 3436", "13 ශ් 3 436", "13 ශ 3 436", "13 ශ්රී 436"
    # Structural bounds: [1-3 leading digits] + [Sinhala Sri cluster] + [1-4 trailing digits]
    m_sin = re.match(
        r"^(\d{1,3})[\s\-_|·•~]*([ශ\u0D80-\u0DFF\u200D\u200C\s\-_|·•~]+)[\s\-_|·•~]*(.*)$",
        norm_text
    )
    if m_sin:
        leading = m_sin.group(1)
        marker_cluster = m_sin.group(2)
        trailing_raw = m_sin.group(3)
        trailing_digits = re.sub(r"\D", "", trailing_raw)
        # Confirm cluster has Sinhala 'Sri' related glyphs (ශ, ර, etc.)
        if any(c in marker_cluster for c in ('ශ', 'ර', '්', 'ී', 'ි')):
            # Ensure it is not a military vehicle (Air Force ගුවන්, Navy නාහ, Army යුහ)
            if not any(k in marker_cluster for k in ('ගුවන්', 'නාහ', 'යුහ', 'ගුවන')):
                # Sri series leading boundary deduplication:
                # Sri Lankan Sri plates are 1-33 (original) or 300-330 (re-registered).
                # If leading is 3 digits (e.g. '133') where the 3rd digit was generated by the left loop of 'ශ',
                # and it's outside the valid 300-series range with repeated boundary digit, collapse to 2 digits.
                if len(leading) == 3:
                    val = int(leading)
                    if val > 33 and not (300 <= val <= 330):
                        if leading[1] == leading[2]:
                            leading = leading[:2]

                if 1 <= len(trailing_digits) <= 4:
                    return f"{leading}-{trailing_digits}", "Sri-Series"

    return None



def basic_clean(text: str) -> str:
    """
    Perform basic whitespace and symbol normalization while preserving Sinhala characters.
    """
    if text is None:
        return ""
    t = str(text).strip()
    t = re.sub(r"[ \t]+", " ", t)
    return t


def remove_prefixes(text: str) -> str:
    """
    Remove known civilian province prefixes ONLY if the remaining string matches
    a valid civilian plate format (2-3 letters + 4 digits) or numeric series (2-3 digits + 4 digits).
    
    Also handles two-line plates with embedded province (e.g. "253 WP 5842" -> "253 5842").
    """
    if not text:
        return text

    t = text.strip()

    # 1. Embedded province on two-line plates (e.g. "253 WP 5842" -> "253 5842")
    for prov in PROVINCES:
        t = re.sub(rf"(\d{{1,3}})[\s\-_|·•~]*{prov}[\s\-_|·•~]*(\d{{4}})", r"\1 \2", t, flags=re.IGNORECASE).strip()

    # 2. Leading province (e.g. "WP CBE 3319" -> "CBE 3319", "WP CBV-3387" -> "CBV-3387")
    for prov in PROVINCES:
        pattern = re.compile(rf"^{prov}[\s\-_|·•~]+(.*)$", re.IGNORECASE)
        m = pattern.match(t)
        if m:
            remainder = m.group(1).strip()
            rem_compact = re.sub(r"[\s\-_|·•~]", "", remainder)
            if re.fullmatch(r"[A-Za-z]{2,3}[0-9]{4}", rem_compact) or re.fullmatch(r"\d{2,3}[0-9]{4}", rem_compact):
                return remainder

    return t


def normalize_modern(text: str) -> Optional[Tuple[str, str]]:
    """
    Check and normalize civilian Modern plates (Modern-3: 3 letters + 4 digits, Modern-2: 2 letters + 4 digits).
    Strictly requires exactly 4 trailing numeric digits. Rejects partial/malformed OCR outputs.
    Returns (normalized_plate, category) or None.
    """
    if not text:
        return None

    cleaned = basic_clean(text)
    # Strip any leading / trailing dashes, dots or garbage punctuation
    cleaned = re.sub(r"^[\s\-_|·•~]+|[\s\-_|·•~]+$", "", cleaned)
    if not cleaned:
        return None

    t = remove_prefixes(cleaned)
    t = re.sub(r"\s*-\s*", "-", t)
    t = re.sub(r"\s+", " ", t).strip()

    # 1. Strict fullmatch with standard space or hyphen:
    # Modern-3: e.g. "CBV-3387", "CBE 3319", "CBL-0676" -> strictly 3 letters + 4 digits
    m3 = re.fullmatch(r"([A-Za-z]{3})[ -]?(\d{4})", t)
    if m3:
        letters = m3.group(1).upper()
        if letters not in PROVINCES:
            return f"{letters}-{m3.group(2)}", "Modern-3"

    # Modern-2: e.g. "GA-1234", "CA 1234", "WP" is excluded
    m2 = re.fullmatch(r"([A-Za-z]{2})[ -]?(\d{4})", t)
    if m2:
        letters = m2.group(1).upper()
        if letters not in PROVINCES:
            return f"{letters}-{m2.group(2)}", "Modern-2"

    # 2. Strict compact fullmatch (no spaces/hyphens):
    compact = re.sub(r"[\s\-_|·•~]", "", t)

    m3_c = re.fullmatch(r"([A-Za-z]{3})(\d{4})", compact)
    if m3_c:
        letters = m3_c.group(1).upper()
        if letters not in PROVINCES:
            return f"{letters}-{m3_c.group(2)}", "Modern-3"

    m2_c = re.fullmatch(r"([A-Za-z]{2})(\d{4})", compact)
    if m2_c:
        letters = m2_c.group(1).upper()
        if letters not in PROVINCES:
            return f"{letters}-{m2_c.group(2)}", "Modern-2"

    # 3. Emblem artifact handling: emblem digit between letters and 4 digits (e.g. "GL-4-1456" -> "GL-1456")
    m_emb = re.fullmatch(r"([A-Za-z]{2,3})[\-_\|·•~]?\d[\-_\|·•~]?(\d{4})", compact)
    if m_emb:
        letters = m_emb.group(1).upper()
        if len(letters) == 3 and letters not in PROVINCES:
            return f"{letters}-{m_emb.group(2)}", "Modern-3"
        elif len(letters) == 2 and letters not in PROVINCES:
            return f"{letters}-{m_emb.group(2)}", "Modern-2"

    # 4. Multi-token / noisy OCR sub-pattern extraction (e.g., "WP-972 WP CBN-2072" -> "CBN-2072")
    # Strictly require word boundaries and exactly 4 numeric digits:
    found_m3 = re.findall(r"(?:^|[^A-Za-z0-9])([A-Za-z]{3})[\s\-_|·•~]*(\d{4})(?:$|[^A-Za-z0-9])", cleaned)
    if found_m3:
        for let, num in reversed(found_m3):
            letters = let.upper()
            if letters not in PROVINCES:
                return f"{letters}-{num}", "Modern-3"

    found_m2 = re.findall(r"(?:^|[^A-Za-z0-9])([A-Za-z]{2})[\s\-_|·•~]*(\d{4})(?:$|[^A-Za-z0-9])", cleaned)
    if found_m2:
        for let, num in reversed(found_m2):
            letters = let.upper()
            if letters not in PROVINCES:
                return f"{letters}-{num}", "Modern-2"

    return None




def normalize_bottom_numeric_strip(text: str) -> str:
    """
    Positional character normalization strictly for the bottom numeric strip of square plates.
    Replaces optical character ambiguities inside numeric positions ONLY.
    Reconstructs 4 registration digits when separated by a center lion hologram seal.
    Never globally replaces letters across the top line.
    """
    if not text:
        return ""
    subs = {
        "O": "0", "o": "0", "D": "0", "Q": "0", "U": "0", "C": "0",
        "I": "1", "L": "1", "i": "1", "l": "1", "|": "1", "!": "1",
        "Z": "2", "z": "2",
        "S": "5", "s": "5",
        "G": "6",
        "B": "8",
    }
    
    # 1. Clean Sinhala seal / symbols and split into words
    t = re.sub(r"[\u0D80-\u0DFF\-_|·•~]+", " ", str(text)).strip()
    words = t.split()
    
    digit_words = []
    for w in words:
        dw = "".join(subs.get(ch, ch) for ch in w if ch.isdigit() or ch in subs)
        if dw:
            digit_words.append(dw)
            
    full_str = "".join(digit_words)
    if len(full_str) == 4:
        return full_str
        
    # 2. Center-Seal Spatial Pair Reconstruction (e.g. ['06', '6', '76'] -> '0676', or ['16', '676'] -> '0676')
    if len(digit_words) >= 2:
        left_pair = digit_words[0]
        right_pair = digit_words[-1]
        
        if len(left_pair) >= 2 and len(right_pair) >= 2:
            left_2 = left_pair[:2]
            if left_2 == "16":
                left_2 = "06"
            right_2 = right_pair[-2:]
            cand = f"{left_2}{right_2}"
            if len(cand) == 4:
                return cand
                
    # 3. Handle 5 digits with split 0 (e.g. '16676' -> '0676', '06676' -> '0676')
    if len(full_str) == 5:
        if full_str.startswith("16") or full_str.startswith("06"):
            return "0" + full_str[2:]
            
    return full_str if len(full_str) == 4 else ""


def parse_two_line_plate(top_raw: str, bot_raw: str) -> Optional[Dict[str, Any]]:
    """
    General Sri Lankan Square / Two-Line Plate Parser.
    Extracts Province + Series from Top Strip and 4 Registration Digits from Bottom Strip.
    Rules:
    - Does NOT hardcode 'WP' (extracts all provinces dynamically or handles plates without province).
    - Strips mounting screw noise and state emblem artifacts.
    - Requires exactly 4 registration digits on bottom; never guesses or truncates characters.
    - Preserves strict validation.
    """
    if not top_raw and not bot_raw:
        return None

    top = str(top_raw).strip().upper()
    bot_digits = normalize_bottom_numeric_strip(bot_raw)

    # 1. Dynamic Province extraction (e.g. 'WP', 'SP', 'CP', etc.)
    found_prov = ""
    top_without_prov = top
    for p in PROVINCES:
        m = re.match(rf"^{p}[\s\-_|·•~]*(.*)$", top)
        if m:
            found_prov = p
            top_without_prov = m.group(1).strip()
            break

    # If full 2-letter province didn't match, check for single leading province initial (W, S, C, N, E, U)
    if not found_prov:
        for sp in {"W", "S", "C", "N", "E", "U"}:
            m = re.match(rf"^{sp}[\s\-_|·•~]+(.*)$", top)
            if m:
                found_prov = sp
                top_without_prov = m.group(1).strip()
                break

    # 2. Extract series letters (2-3 letters, e.g. 'CBL', 'KS', 'CAB', 'GA')
    # Discards trailing mounting bolt noise (e.g. 'BL-81' -> 'BL', 'KS--8684' -> 'KS')
    clean_top_letters = re.sub(r"[\d\-_|·•~\s]", "", top_without_prov).strip()

    # Sri Lankan civilian series letters never start with 'W' (W is exclusively Western Province)
    if clean_top_letters.startswith("W") and len(clean_top_letters) > 1:
        clean_top_letters = clean_top_letters[1:]

    series_letters = ""
    if 2 <= len(clean_top_letters) <= 3 and clean_top_letters not in PROVINCES:
        series_letters = clean_top_letters
    else:
        letters_match = re.findall(r"[A-Z]{2,3}", top_without_prov)
        if letters_match:
            for let in letters_match:
                if let not in PROVINCES and not let.startswith("W"):
                    series_letters = let
                    break

    # 3. Vintage series digits check (e.g. '301', '15', '32')
    vintage_digits = re.findall(r"^\d{1,3}", re.sub(r"[\s\-_]", "", top_without_prov))
    series_digits = vintage_digits[0] if vintage_digits else ""

    # 4. Strictly require exactly 4 registration digits on bottom strip
    if series_letters and len(bot_digits) == 4:
        cat = "Modern-3" if len(series_letters) == 3 else "Modern-2"
        norm = f"{series_letters}-{bot_digits}"
        return {
            "raw_plate": f"{top} {bot_raw}".strip(),
            "normalized_plate": norm,
            "province": found_prov,
            "plate_category": cat,
            "valid": True,
            "status": "VALID",
            "text": norm,
            "type": cat
        }
    elif series_digits and len(bot_digits) == 4:
        norm = f"{series_digits}-{bot_digits}"
        return {
            "raw_plate": f"{top} {bot_raw}".strip(),
            "normalized_plate": norm,
            "province": "",
            "plate_category": "Numeric",
            "valid": True,
            "status": "VALID",
            "text": norm,
            "type": "Numeric"
        }

    # Incomplete or non-4-digit candidate: held in PENDING_OCR for temporal accumulation
    combined_raw = f"{top} {bot_raw}".strip()
    return {
        "raw_plate": combined_raw,
        "normalized_plate": combined_raw,
        "province": found_prov,
        "plate_category": "Pending-Square",
        "valid": False,
        "status": "PENDING_OCR",
        "text": combined_raw,
        "type": "Pending-Square"
    }


def normalize_vintage_numeric(cleaned: str) -> Optional[Tuple[str, str]]:
    """
    Safely parse Sri Lankan vintage numeric plates (e.g. 301-3949, 15-3201).
    Strict rules:
    - If any alphabetic letters exist, return None (handled by modern/military).
    - Extract all digits.
    - Exactly 7 digits -> XXX-XXXX (3 leading + 4 trailing) -> VALID
    - Exactly 6 digits -> XX-XXXX (2 leading + 4 trailing) -> VALID
    - Anything else (0-5 digits, 8+ digits) -> None (classified as Incomplete or Invalid).
    """
    if not cleaned:
        return None

    # Strip valid province prefix if present (e.g., "WP 301 3949")
    t = remove_prefixes(cleaned)
    t = re.sub(r"[\s\-_|·•~]+", " ", t).strip()

    # If non-province letters exist, it is not a pure vintage numeric plate
    has_letters = bool(re.search(r"[A-Za-z\u0D80-\u0DFF]", t))
    if has_letters:
        return None

    # Extract all digits
    digits = re.findall(r"\d", t)
    digit_count = len(digits)
    digit_str = "".join(digits)

    if digit_count == 7:
        return f"{digit_str[:3]}-{digit_str[3:]}", "Numeric"
    elif digit_count == 6:
        return f"{digit_str[:2]}-{digit_str[2:]}", "Numeric"

    return None


def check_pending_or_incomplete(cleaned: str) -> Optional[Tuple[str, str]]:
    """
    Detect pending OCR candidate streams (e.g. noisy 10 digits from screw holes '30 41014 32 949',
    or partial reads 'CAT-687', '301', 'WP BO- -391').
    Returns (candidate_string, category) to allow temporal voting to accumulate frames.
    DO NOT guess missing digits or open gates.
    """
    if not cleaned:
        return None
    t = remove_prefixes(cleaned)
    t = re.sub(r"\s*-\s*", "-", t)
    compact = re.sub(r"[\s\-_|·•~]", "", t)

    # 1. Partial modern plates (e.g. CAT-687, CA-123)
    m_inc = re.fullmatch(r"([A-Za-z]{2,3})[ -]?(\d{1,3})", t)
    if m_inc:
        letters = m_inc.group(1).upper()
        if letters not in PROVINCES:
            return f"{letters}-{m_inc.group(2)}", "Pending-Modern"

    m_inc_c = re.fullmatch(r"([A-Za-z]{2,3})(\d{1,3})", compact)
    if m_inc_c:
        letters = m_inc_c.group(1).upper()
        if letters not in PROVINCES:
            return f"{letters}-{m_inc_c.group(2)}", "Pending-Modern"

    # Multi-token sub-pattern incomplete extraction
    found_inc = re.findall(r"(?:^|[^A-Za-z0-9])([A-Za-z]{2,3})[\s\-_|·•~]*(\d{1,3})(?:$|[^A-Za-z0-9])", cleaned)
    if found_inc:
        for let, num in reversed(found_inc):
            letters = let.upper()
            if letters not in PROVINCES:
                return f"{letters}-{num}", "Pending-Modern"

    # 2. Noisy / Multi-digit / Partial Numeric (e.g. '30 41014 32 949', '301', '15-32')
    digits = re.findall(r"\d", t)
    if len(digits) >= 2:
        return "".join(digits), "Pending-Numeric"

    return None


def normalize_plate(text: str) -> Dict[str, Any]:
    """
    Master normalization function for Sri Lankan vehicle plates.
    
    Processing order:
    1. Basic OCR cleaning
    2. Sri Series detection
    3. Military detection
    4. Civilian province detection & Modern normalization
    5. Strict 6/7-Digit Vintage Numeric detection
    6. Pending / Incomplete Candidate Detection (PENDING_OCR, for temporal voter)
    7. Invalid / Completely Unrecognized handling
    """
    raw_plate = text if text is not None else ""
    cleaned = basic_clean(raw_plate)

    if not cleaned:
        return {
            "raw_plate": raw_plate,
            "normalized_plate": "",
            "plate_category": "Unknown",
            "valid": False,
            "status": "INVALID",
            "text": "",
            "type": "Unknown"
        }

    # ---------------------------------------------------------
    # 1. Sri Series Detection (Dedicated Sri-Marker normalization)
    # ---------------------------------------------------------
    sri_result = normalize_sri_series(cleaned)
    if sri_result:
        norm, category = sri_result
        return {
            "raw_plate": raw_plate,
            "normalized_plate": norm,
            "plate_category": category,
            "valid": True,
            "status": "VALID",
            "text": norm,
            "type": category
        }

    # ---------------------------------------------------------
    # 2. Military Detection (Sinhala and English variations)
    # ---------------------------------------------------------
    # Air Force
    m_air_sin = AIR_FORCE_SINHALA.match(cleaned)
    if m_air_sin:
        norm = f"AIR-{m_air_sin.group(1)}"
        return {
            "raw_plate": raw_plate,
            "normalized_plate": norm,
            "plate_category": "Air Force",
            "valid": True,
            "status": "VALID",
            "text": norm,
            "type": "Air Force"
        }
    m_air_eng = AIR_FORCE_ENGLISH.match(cleaned)
    if m_air_eng:
        norm = f"AIR-{m_air_eng.group(1)}"
        return {
            "raw_plate": raw_plate,
            "normalized_plate": norm,
            "plate_category": "Air Force",
            "valid": True,
            "status": "VALID",
            "text": norm,
            "type": "Air Force"
        }

    # Navy
    m_navy_sin = NAVY_SINHALA.match(cleaned)
    if m_navy_sin:
        norm = f"NAVY-{m_navy_sin.group(1)}"
        return {
            "raw_plate": raw_plate,
            "normalized_plate": norm,
            "plate_category": "Navy",
            "valid": True,
            "status": "VALID",
            "text": norm,
            "type": "Navy"
        }
    m_navy_eng = NAVY_ENGLISH.match(cleaned)
    if m_navy_eng:
        norm = f"NAVY-{m_navy_eng.group(1)}"
        return {
            "raw_plate": raw_plate,
            "normalized_plate": norm,
            "plate_category": "Navy",
            "valid": True,
            "status": "VALID",
            "text": norm,
            "type": "Navy"
        }

    # Army
    m_army_sin = ARMY_SINHALA.match(cleaned)
    if m_army_sin:
        norm = f"ARMY-{m_army_sin.group(1)}"
        return {
            "raw_plate": raw_plate,
            "normalized_plate": norm,
            "plate_category": "Army",
            "valid": True,
            "status": "VALID",
            "text": norm,
            "type": "Army"
        }
    m_army_eng = ARMY_ENGLISH.match(cleaned)
    if m_army_eng:
        norm = f"ARMY-{m_army_eng.group(1)}"
        return {
            "raw_plate": raw_plate,
            "normalized_plate": norm,
            "plate_category": "Army",
            "valid": True,
            "status": "VALID",
            "text": norm,
            "type": "Army"
        }

    # ---------------------------------------------------------
    # 3. Civilian Modern Plates (Modern-2 and Modern-3)
    # ---------------------------------------------------------
    modern_res = normalize_modern(cleaned)
    if modern_res:
        norm_plate, category = modern_res
        return {
            "raw_plate": raw_plate,
            "normalized_plate": norm_plate,
            "plate_category": category,
            "valid": True,
            "status": "VALID",
            "text": norm_plate,
            "type": category
        }

    # ---------------------------------------------------------
    # 4. Strict 6/7-Digit Vintage Numeric (e.g. 301 3949 -> 301-3949, 15 3201 -> 15-3201)
    # ---------------------------------------------------------
    vint_res = normalize_vintage_numeric(cleaned)
    if vint_res:
        norm_plate, category = vint_res
        return {
            "raw_plate": raw_plate,
            "normalized_plate": norm_plate,
            "plate_category": category,
            "valid": True,
            "status": "VALID",
            "text": norm_plate,
            "type": category
        }

    # ---------------------------------------------------------
    # 5. Pending / Incomplete Candidate Detection (PENDING_OCR, for temporal voter)
    # ---------------------------------------------------------
    pend_res = check_pending_or_incomplete(cleaned)
    if pend_res:
        norm_pend, cat_pend = pend_res
        return {
            "raw_plate": raw_plate,
            "normalized_plate": norm_pend,
            "plate_category": cat_pend,
            "valid": False,
            "status": "PENDING_OCR",
            "text": norm_pend,
            "type": cat_pend
        }

    # ---------------------------------------------------------
    # 6. Invalid / Completely Unrecognized Plate
    # ---------------------------------------------------------
    return {
        "raw_plate": raw_plate,
        "normalized_plate": "",
        "plate_category": "Unknown",
        "valid": False,
        "status": "INVALID",
        "text": "",
        "type": "Unknown"
    }


class PlateValidator:
    """
    Plate Validator and Normalizer Class.
    Integrated with OCR reader, retry engine, and backend.
    """

    def __init__(self):
        self.patterns = {
            "Modern3": re.compile(r"^[A-Z]{3}-\d{4}$"),
            "Modern2": re.compile(r"^[A-Z]{2}-\d{4}$"),
            "Numeric": re.compile(r"^\d{2,3}-\d{4}$"),
            "Sri-Series": re.compile(r"^\d{1,3}-\d{1,4}$"),
            "Army": re.compile(r"^ARMY-\d{4,5}$"),
            "Navy": re.compile(r"^NAVY-\d{4,5}$"),
            "Air Force": re.compile(r"^AIR-\d{4,5}$"),
        }

    def validate(self, text: str) -> Dict[str, Any]:
        """
        Validate and normalize OCR text.
        Returns dictionary with validation and normalization status.
        """
        if text is None:
            return {
                "valid": False,
                "status": "INVALID",
                "type": "Unknown",
                "text": "",
                "raw_plate": "",
                "normalized_plate": "",
                "plate_category": "Unknown"
            }

        # Run master normalization
        norm_res = normalize_plate(text)
        return norm_res

    def normalize(self, text: str) -> Dict[str, Any]:
        """
        Alias to normalize_plate.
        """
        return normalize_plate(text)